### ISSUE TITLE
It's alive !

### ISSUE THREAD

**Issue by stuaxo** [alexlarsson/gthree#16]
Just want to +1 on this project.   It's a nice surprise coming back from Libre Graphics Meeting, to see this project get some commits :)

**Comment by alexlarsson** [comment]
Thanks!
I want to use it to make some gnome easter egg kind of thing. You don't happen to know someone who can do 3d character modeling? Say a gegl or a wanda the fish model?

**Comment by stuaxo** [comment]
I do, but they are usually busy, will ask..

**Comment by alexlarsson** [comment]
It doesn't have to be super high quality, but it would be cool to have something gnome specific...

**Comment by stuaxo** [comment]
In the meantime, I would recommend investigating zdog - you can make pseudo3d with only 2d skills - no idea how easy it is to export.

**Comment by alexlarsson** [comment]
Or i just make really really ugly programmer art, forcing the hand of any sane designers! HA!
