### ISSUE TITLE
examples/models crashes when unrealizing scene when switching models

### ISSUE THREAD

**Issue by alexlarsson** [alexlarsson/gthree#23]
The code currently has the unref commented out, but it it is enabled again we crash when switching models.

**Comment by alexlarsson** [comment]
This is now fixed

**Comment by stuaxo** [comment]
Is there some way of building running the examples (say for just one frame each) + to verify they run, for CI ?

**Comment by alexlarsson** [comment]
@stuaxo not currently, but it could be added i guess. One problem is that CI often doesn't have access to OpenGL as it needs an entire X server or similar.
