### ISSUE TITLE
Cant build after this commit

### ISSUE THREAD

**Issue by tim77** [alexlarsson/gthree#45]
Hello Alex.

https://github.com/alexlarsson/gthree/commit/a38a2313ab672ce0d09f15f69077577341127553 build fine, but next commit https://github.com/alexlarsson/gthree/commit/209238537d1fb0c4f632e232b088a02bba2e517e build fail. :)

Build log:

```
/usr/bin/ld: gthree/a0bd3e6@@gthree-1@sha/gthreerenderer.c.o: in function `project_planes':
/builddir/build/BUILD/alexlarsson-gthree-2092385/x86_64-redhat-linux-gnu/../gthree/gthreerenderer.c:1214: undefined reference to `graphene_plane_transform'
collect2: error: ld returned 1 exit status
```

**Comment by tim77** [comment]
Ah, this probably because we need latest **graphene**
https://github.com/ebassi/graphene/releases/tag/1.9.6

**Comment by alexlarsson** [comment]
Yeah, graphene got the function so might as well use it from there.
