### ISSUE TITLE
autogen sh build failure/help

### ISSUE THREAD

**Issue by thorsummoner** [alexlarsson/gthree#5]
Got the following complaint:

```
configure.ac:7: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

Full log: https://gist.github.com/thorsummoner/4468b95a91fb4b1d05cc

**Comment by alexlarsson** [comment]
I can't say i understand this, but i pushed some cleanups to the configure.ac that may have helped.

**Comment by thorsummoner** [comment]
I'm uninterested in confirming this issue, if a future person discovered further issue, opening a new thread would be appropriate
