### ISSUE TITLE
Search paths for Graphene-1.0.gir doesn't include /usr/local

### ISSUE THREAD

**Issue by procedural** [alexlarsson/gthree#6]
Make error:
```
Couldn't find include 'Graphene-1.0.gir' (search path: ['gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0'])
/usr/share/gobject-introspection-1.0/Makefile.introspection:153: recipe for target 'Gthree-1.0.gir' failed
```
I've installed Graphene to `/usr/local` folder, its .gir file was placed by `make install` command here:
```
/usr/local/share/gir-1.0/Graphene-1.0.gir
```

**Comment by alexlarsson** [comment]
Yeah, this seems like a bug in gobject-introspection. It is supposed to look at XDG_DATA_DIRS, and according to the spec at http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html:

    If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used. 

But, the fallback in gobject-introspection is only using /usr/share as fallback.

That said, you can work around this by setting XDG_DATA_DIRS to  "/usr/local/share/:/usr/share/"

**Comment by alexlarsson** [comment]
Filed the g-i bug at https://bugzilla.gnome.org/show_bug.cgi?id=750543

**Comment by procedural** [comment]
@alexlarsson thank you for filing the bug! I knew there must be a global variable for search dirs, I just didn't knew it's name.

Thanks again! I'll use XDG_DATA_DIRS for now.
