### ISSUE TITLE
Error when running ./autogen.sh without installed GObject Introspection

### ISSUE THREAD

**Issue by procedural** [alexlarsson/gthree#7]
```
gthree/Makefile.am:179: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
autoreconf: automake failed with exit status: 1
```

**Comment by procedural** [comment]
Since https://github.com/alexlarsson/gthree/pull/4 introspection is required now?

**Comment by procedural** [comment]
216b0c4, a commit before #4 compiles fine.

**Comment by alexlarsson** [comment]
Well, it uses the GOBJECT_INTROSPECTION_CHECK macro, so its necessary if you build from git i guess. Its not needed for the generated tarball. Of course, there are not really a release tarball out.

If you really don't want to install gobject-introspection, you can put https://git.gnome.org/browse/gobject-introspection/tree/m4/introspection.m4 into the m4 subdirectory.

**Comment by procedural** [comment]
@alexlarsson no, I'm fine having it, this issue was more of a possible workaround for issue #6 

Thanks!
